In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store/2019-Nov.csv
/kaggle/input/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store/2019-Oct.csv
/kaggle/input/datasets/dyuthivivek/ecommerce-recsys-sequences/category_mappings.json
/kaggle/input/datasets/dyuthivivek/ecommerce-recsys-sequences/e-commerce_sequences.jsonl

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/kaggle/input/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store/2019-Nov.csv')

In [3]:
df2 = pd.read_csv('/kaggle/input/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store/2019-Oct.csv')

In [4]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

In [5]:
df['user_id'].nunique()

3696117

In [6]:
df2.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [7]:
df = pd.concat([df, df2])

In [8]:
len(df)

109950743

In [9]:
del df2

In [10]:
user_wise = df.groupby('user_id').count()

In [11]:
user_wise.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_session
user_id,,,,,,,,
10300217,1,1,1,1,0,1,1,1
29515875,11,11,11,11,11,7,11,11
31198833,20,20,20,20,19,20,20,20
33869381,1,1,1,1,1,1,1,1
34916060,1,1,1,1,1,1,1,1

user_wise['category_code'].describe()

In [12]:
user_wise = user_wise[user_wise['category_code'] >= 12]

In [13]:
user_wise.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_session
user_id,,,,,,,,
31198833,20,20,20,20,19,20,20,20
62336140,19,19,19,19,19,6,19,19
94566147,22,22,22,22,22,22,22,22
96041329,43,43,43,43,43,42,43,43
107837897,32,32,32,32,32,31,32,32

In [14]:
index_list = user_wise.index.tolist()

In [15]:
users = set(index_list)

In [16]:
df = df[df['user_id'].isin(users)]

In [17]:
del users
del index_list
del user_wise

In [18]:
len(df)

86318262

In [19]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
5,2019-11-01 00:00:01 UTC,view,1306894,2053013558920217191,computers.notebook,hp,360.09,520772685,816a59f3-f5ae-4ccd-9b23-82aa8c23d33c
6,2019-11-01 00:00:01 UTC,view,1306421,2053013558920217191,computers.notebook,hp,514.56,514028527,df8184cc-3694-4549-8c8c-6b5171877376

In [20]:
df = df.dropna(subset=['category_code'])

In [21]:
len(df)

63764619

In [22]:
df['event_type'].value_counts()

event_type
view        60009993
cart         2674796
purchase     1079830
Name: count, dtype: int64

In [23]:
df = df[df['event_type'] == 'view']

In [24]:
len(df)

60009993

In [25]:
import json

prod_cat_df = df[['product_id', 'category_id']].dropna().drop_duplicates()
product_to_category = dict(zip(prod_cat_df['product_id'].astype(str), prod_cat_df['category_id'].astype(str)))

cat_code_df = df[['category_id', 'category_code']].dropna().drop_duplicates()
category_to_code = dict(zip(cat_code_df['category_id'].astype(str), cat_code_df['category_code'].astype(str)))

mappings = {
    "product_to_category": product_to_category,
    "category_to_code": category_to_code
}

with open('category_mappings.json', 'w') as f:
    json.dump(mappings, f, indent=4)

In [26]:
del prod_cat_df
del cat_code_df
del product_to_category
del category_to_code
del mappings

In [27]:
cols_to_keep = ['user_id', 'product_id', 'event_time']
df = df[cols_to_keep] 

df['user_id'] = df['user_id'].astype('category')
df['event_time'] = pd.to_datetime(df['event_time'], format='%Y-%m-%d %H:%M:%S UTC')
df.sort_values(by=['user_id', 'event_time'], inplace=True, ignore_index=True)

In [28]:
df['time_str'] = df['event_time'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [29]:
all_products = df['product_id'].dropna().unique().tolist()

In [30]:
def sample_negatives(target, all_prods, k):
    negs = set()
    while len(negs) < k:
        candidate = str(random.choice(all_prods))
        if candidate != target:
            negs.add(candidate)
    return list(negs)

In [31]:
import json
import random

window_size = 15
num_negatives = 100


df['product_id'] = df['product_id'].astype(str)
df['time_str'] = df['time_str'].astype(str) 

output_filepath = 'e-commerce_sequences.jsonl'

# 3 GB limit in bytes (3 * 1024 * 1024 * 1024)
MAX_BYTES = 3 * 1024 * 1024 * 1024 
bytes_written = 0
records_saved = 0
limit_reached = False

with open(output_filepath, 'w', encoding='utf-8') as f:
    
    # Iterate over the groups
    for user, group in df.groupby('user_id', observed=True):
        if limit_reached:
            break
            
        if len(group) < (window_size + 2):
            continue
            
        products = group['product_id'].tolist()
        timestamps = group['time_str'].tolist()
        
        start_idx = window_size + 1 
        
        for i in range(start_idx, len(products)):
            target_item = products[i]
            
            negative_items = sample_negatives(target_item, all_products, num_negatives)
            
            record = {
                'user_id': str(user),
                'slow_memory_ids': products[0 : i - window_size],
                'slow_id_timestamps': timestamps[0 : i - window_size],
                'fast_memory_ids': products[i - window_size : i],
                'fast_id_timestamps': timestamps[i - window_size : i],
                'target_item': target_item,
                'target_timestamp': timestamps[i],
                'negative_items': negative_items
            }
            
            line_to_write = json.dumps(record) + '\n'
            
            line_size = len(line_to_write.encode('utf-8'))
            
            # Check if writing this line exceeds our 3 GB limit
            if bytes_written + line_size > MAX_BYTES:
                limit_reached = True
                break  # Break inner loop
            
            f.write(line_to_write)
            bytes_written += line_size
            records_saved += 1

print(f"Done! Dataset saved memory-safely to '{output_filepath}'.")
print(f"Total disk space used: {bytes_written / (1024**3):.4f} GB")
print(f"Total data points saved: {records_saved:,}")

Done! Dataset saved memory-safely to 'e-commerce_sequences.jsonl'.
Total disk space used: 3.0000 GB
Total data points saved: 272,074

In [1]:
import json

data = []
with open('e-commerce_sequences.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        data.append(json.loads(line))

In [2]:
len(data)

272074

In [6]:
data[1001]

{'user_id': '296653461',
 'slow_memory_ids': ['19100001',
  '19100174',
  '19100036',
  '19100039',
  '19100038',
  '19100038',
  '19100174',
  '19100174',
  '19100038',
  '19100039',
  '19100037',
  '19100052',
  '19100207',
  '19100299',
  '19100393',
  '19100298',
  '19100348',
  '19100214',
  '19100058',
  '19100003',
  '19100174',
  '19100235',
  '19100039',
  '19100175',
  '19100175'],
 'slow_id_timestamps': ['2019-11-11 15:01:03',
  '2019-11-11 15:02:56',
  '2019-11-11 15:04:11',
  '2019-11-11 15:04:59',
  '2019-11-11 15:06:48',
  '2019-11-11 15:07:28',
  '2019-11-11 15:08:06',
  '2019-11-11 15:09:06',
  '2019-11-11 15:09:38',
  '2019-11-11 15:09:47',
  '2019-11-11 15:11:12',
  '2019-11-11 15:11:31',
  '2019-11-11 15:12:01',
  '2019-11-11 15:13:19',
  '2019-11-11 15:13:42',
  '2019-11-11 15:14:40',
  '2019-11-11 15:16:37',
  '2019-11-11 15:18:03',
  '2019-11-11 15:18:44',
  '2019-11-11 15:19:43',
  '2019-11-11 15:20:57',
  '2019-11-11 15:22:28',
  '2019-11-11 15:23:36',
  '2019-11-11 15:25:04',
  '2019-11-11 15:53:44'],
 'fast_memory_ids': ['19100039',
  '19100175',
  '19100175',
  '19100175',
  '19100039',
  '19100038',
  '19100039',
  '19100175',
  '19100039',
  '19100235',
  '19100039',
  '19100174',
  '19100176',
  '19100335',
  '19100036'],
 'fast_id_timestamps': ['2019-11-11 15:56:27',
  '2019-11-11 15:56:45',
  '2019-11-11 17:36:25',
  '2019-11-11 18:03:26',
  '2019-11-11 18:03:37',
  '2019-11-11 18:04:07',
  '2019-11-11 18:04:34',
  '2019-11-11 18:04:46',
  '2019-11-11 18:04:59',
  '2019-11-11 18:06:11',
  '2019-11-11 18:07:24',
  '2019-11-11 18:08:00',
  '2019-11-11 18:09:38',
  '2019-11-11 18:10:33',
  '2019-11-11 18:11:31'],
 'target_item': '19100362',
 'target_timestamp': '2019-11-11 18:12:08',
 'negative_items': ['28711545',
  '8700279',
  '59500005',
  '17200525',
  '27701041',
  '8901544',
  '22600072',
  '1700468',
  '3900969',
  '44300077',
  '30900708',
  '18200004',
  '4400426',
  '3900913',
  '47200196',
  '100010917',
  '28711529',
  '21411003',
  '28720586',
  '17800112',
  '21403695',
  '100004624',
  '28721500',
  '28300129',
  '3100605',
  '29600041',
  '21404422',
  '21408079',
  '2702340',
  '45600460',
  '28704937',
  '8902402',
  '1700845',
  '28718555',
  '100008211',
  '35104844',
  '3700863',
  '28719181',
  '21401517',
  '8700252',
  '5000679',
  '13500015',
  '7900760',
  '44800073',
  '28400544',
  '7901120',
  '11100164',
  '2702539',
  '100004311',
  '100009227',
  '17900256',
  '21409885',
  '5700453',
  '5801344',
  '56300126',
  '7001172',
  '21408659',
  '1802118',
  '4802680',
  '8901535',
  '13901858',
  '12900285',
  '13600022',
  '21409678',
  '6902469',
  '4501173',
  '100014155',
  '21407662',
  '5800861',
  '1700872',
  '35108836',
  '28708264',
  '28718923',
  '3200339',
  '13500128',
  '7901018',
  '100009333',
  '27700062',
  '2700859',
  '28714600',
  '13201151',
  '4502746',
  '8801114',
  '35103099',
  '17800037',
  '27700944',
  '56300047',
  '3200163',
  '6200948',
  '14100543',
  '20500475',
  '21409828',
  '18300580',
  '28716719',
  '6700809',
  '1004801',
  '1306612',
  '21411940',
  '9700280',
  '6900914']}

In [8]:
!mkdir -p e-commerce_dataset
!mv e-commerce_sequences.jsonl e-commerce_dataset/

In [9]:
!ls

category_mappings.json	e-commerce_dataset

In [10]:
!kaggle datasets init -p e-commerce_dataset/

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.2)
Data package template written to: e-commerce_dataset/dataset-metadata.json

In [22]:
!kaggle datasets create -p e-commerce_dataset/ --dir-mode zip

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.2)
Starting upload for file category_mappings.json
100%|██████████████████████████████████████| 3.57M/3.57M [00:01<00:00, 3.04MB/s]
Upload successful: category_mappings.json (4MB)
Starting upload for file e-commerce_sequences.jsonl
Error while trying to load upload info: KaggleObject.from_dict() got an unexpected keyword argument 'token'
100%|██████████████████████████████████████| 3.00G/3.00G [01:24<00:00, 38.2MB/s]
Upload successful: e-commerce_sequences.jsonl (3GB)
Your private Dataset is being created. Please check progress at https://www.kaggle.com/datasets/dyuthivivek/ecommerce-recsys-sequences

In [12]:
!ls e-commerce_dataset/

dataset-metadata.json  e-commerce_sequences.jsonl

In [13]:
import json
with open('e-commerce_dataset/dataset-metadata.json', 'r') as f:
    a = json.load(f)

In [14]:
a

{'title': 'INSERT_TITLE_HERE',
 'id': 'dyuthivivek/INSERT_SLUG_HERE',
 'licenses': [{'name': 'CC0-1.0'}]}

In [15]:
a['title'] = "E-Commerce RecSys Sequences"

In [16]:
a['id'] = 'dyuthivivek/ecommerce-recsys-sequences'

In [17]:
a

{'title': 'E-Commerce RecSys Sequences',
 'id': 'dyuthivivek/ecommerce-recsys-sequences',
 'licenses': [{'name': 'CC0-1.0'}]}

In [18]:
import json
with open('e-commerce_dataset/dataset-metadata.json', 'w') as f:
    json.dump(a, f)

In [21]:
!mv category_mappings.json e-commerce_dataset/